on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrdemo1989.azurecr.io
        username: ${{ secrets.acr_acrdemo1989_username }}
        password: ${{ secrets.acr_acrdemo1989_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrdemo1989.azurecr.io/aksdemo1:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrdemo1989.azurecr.io/aksdemo1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdemo1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-demo-1b290 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-demo-1b290`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-demo-1b290
        container-registry-url: acrdemo1989.azurecr.io
        container-registry-username: ${{ secrets.acr_acrdemo1989_username }}
        container-registry-password: ${{ secrets.acr_acrdemo1989_password }}
        secret-name: aksdemo1dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-demo-1b290
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          acrdemo1989.azurecr.io/aksdemo1:${{ github.sha }}
        imagepullsecrets: |
          aksdemo1dockerauth
